name: CI

on: [pull_request]

jobs:
  setup:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Launch Turbo Remote Cache Server
        uses: dtinth/setup-github-actions-caching-for-turbo@v1

      - name: Prepare Environment
        run: cp apps/admin/.env.tmpl apps/admin/.env

      - name: Install pnpm
        run: pnpm install

  lint:
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Run Linting
        run: pnpm lint:check

  format:
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Run Formatting
        run: pnpm format:check

  build:
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Build Project
        run: pnpm build
